#
# Inspired by justinsteven's jax... a replacement for my kali VM
#

FROM bnsec-auto-matator:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN yum install -y \
	tmux \
	vim \
	zsh

COPY ./dotfiles/.gitconfig /root/.gitconfig
COPY ./dotfiles/.mylscolors /root/.mylscolors
COPY ./dotfiles/.tmux.conf /root/.tmux.conf
COPY ./dotfiles/.vimrc /root/.vimrc
COPY ./dotfiles/.zshrc /root/.zshrc
COPY ./dotfiles/desert.vim /root/.vim/colors/desert.vim

CMD ["/bin/zsh"]

